defmodule Dfoto.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:images, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :photographer_guest_name, :text
      add :taken_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
      add :is_thumbnail, :boolean

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :album_id, :uuid
      add :photographer_id, :uuid
      add :user_id, :uuid
    end

    create table(:albums, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:images) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "images_album_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :photographer_id,
             references(:users,
               column: :id,
               name: "images_photographer_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "images_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:images, [:album_id],
             name: "images_single_thumbnail_index",
             where: "(is_thumbnail)"
           )

    alter table(:albums) do
      add :title, :text
      add :description, :text
      add :state, :text, default: "draft"
      add :start_at, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:albums) do
      remove :modified_at
      remove :created_at
      remove :start_at
      remove :state
      remove :description
      remove :title
    end

    drop_if_exists unique_index(:images, [:album_id], name: "images_single_thumbnail_index")

    drop constraint(:images, "images_album_id_fkey")

    drop constraint(:images, "images_photographer_id_fkey")

    drop constraint(:images, "images_user_id_fkey")

    alter table(:images) do
      modify :user_id, :uuid
      modify :photographer_id, :uuid
      modify :album_id, :uuid
    end

    drop table(:albums)

    drop table(:images)
  end
end
