defmodule Dfoto.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      modify :id, :bigserial, default: nil
    end

    create table(:image, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :photographer_guest_name, :text
      add :taken_at, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')")
      add :is_thumbnail, :boolean

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :album_id, :bigint
      add :photographer_id, :bigint
      add :user_id, :bigint
    end

    create table(:album, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
    end

    alter table(:image) do
      modify :album_id,
             references(:album,
               column: :id,
               name: "image_album_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :photographer_id,
             references(:users,
               column: :id,
               name: "image_photographer_id_fkey",
               type: :bigint,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "image_user_id_fkey",
               type: :bigint,
               prefix: "public"
             )
    end

    create unique_index(:image, [:album_id],
             name: "image_single_thumbnail_index",
             where: "(is_thumbnail)"
           )

    alter table(:album) do
      add :title, :text
      add :description, :text
      add :state, :text, default: "draft"
      add :start_at, :utc_datetime

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :modified_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:album) do
      remove :modified_at
      remove :created_at
      remove :start_at
      remove :state
      remove :description
      remove :title
    end

    drop_if_exists unique_index(:image, [:album_id], name: "image_single_thumbnail_index")

    drop constraint(:image, "image_album_id_fkey")

    drop constraint(:image, "image_photographer_id_fkey")

    drop constraint(:image, "image_user_id_fkey")

    alter table(:image) do
      modify :user_id, :bigint
      modify :photographer_id, :bigint
      modify :album_id, :bigint
    end

    drop table(:album)

    drop table(:image)

    alter table(:users) do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end
end
