defmodule Dfoto.Repo.Migrations.MigrateResources6 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images) do
      modify :is_thumbnail, :boolean, null: false, default: false
      modify :taken_at, :utc_datetime, null: false
      add :filename, :text
      add :mimetype, :text
    end
  end

  def down do
    alter table(:images) do
      remove :mimetype
      remove :filename
      modify :taken_at, :utc_datetime, null: true
      modify :is_thumbnail, :boolean, null: true, default: nil
    end
  end
end
