defmodule Dfoto.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE INDEX albums_search_idx ON albums USING GIN (to_tsvector('swedish_hunspell', title || ' ' || description));
    """)
  end

  def down do
    execute("""
    DROP INDEX albums_search_idx;
    """)
  end
end
