defmodule Dfoto.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:legacy_images, primary_key: false) do
      add :legacy_id, :text, null: false

      add :id,
          references(:images,
            column: :id,
            name: "legacy_images_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create unique_index(:legacy_images, [:legacy_id],
             name: "legacy_images_unique_legacy_id_index"
           )

    create table(:legacy_albums, primary_key: false) do
      add :legacy_id, :text, null: false

      add :id,
          references(:albums,
            column: :id,
            name: "legacy_albums_id_fkey",
            type: :uuid,
            prefix: "public"
          ), primary_key: true, null: false
    end

    create unique_index(:legacy_albums, [:legacy_id],
             name: "legacy_albums_unique_legacy_id_index"
           )

    alter table(:images) do
      add :version, :bigint, null: false, default: 1
    end

    alter table(:albums) do
      add :version, :bigint, null: false, default: 1
    end
  end

  def down do
    alter table(:albums) do
      remove :version
    end

    alter table(:images) do
      remove :version
    end

    drop_if_exists unique_index(:legacy_albums, [:legacy_id],
                     name: "legacy_albums_unique_legacy_id_index"
                   )

    drop constraint(:legacy_albums, "legacy_albums_id_fkey")

    drop table(:legacy_albums)

    drop_if_exists unique_index(:legacy_images, [:legacy_id],
                     name: "legacy_images_unique_legacy_id_index"
                   )

    drop constraint(:legacy_images, "legacy_images_id_fkey")

    drop table(:legacy_images)
  end
end
