defmodule Dfoto.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :authentik_id, :text, null: false
      add :name, :text, null: false
    end

    create unique_index(:users, [:authentik_id], name: "users_authentik_id_index")

    rename table(:albums), :state, to: :status

    alter table(:albums) do
      modify :status, :text, null: false
      modify :description, :text, null: false
      modify :title, :text, null: false
    end
  end

  def down do
    alter table(:albums) do
      modify :title, :text, null: true
      modify :description, :text, null: true
      modify :status, :text, null: true
    end

    rename table(:albums), :status, to: :state

    drop_if_exists unique_index(:users, [:authentik_id], name: "users_authentik_id_index")

    alter table(:users) do
      remove :name
      remove :authentik_id
    end
  end
end
