defmodule Dfoto.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:images) do
      remove :is_thumbnail
      remove :mimetype
    end

    drop_if_exists unique_index(:images, [:album_id], name: "images_single_thumbnail_index")
  end

  def down do
    create unique_index(:images, [:album_id],
             name: "images_single_thumbnail_index",
             where: "(is_thumbnail)"
           )

    alter table(:images) do
      add :mimetype, :text
      add :is_thumbnail, :boolean, null: false, default: false
    end
  end
end
