defmodule Dfoto.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE TEXT SEARCH DICTIONARY swedish_hunspell (
      Template = ispell,
      DictFile = sv_se,
      AffFile = sv_se,
      Stopwords = swedish
    );

    CREATE TEXT SEARCH CONFIGURATION swedish_hunspell (copy = pg_catalog.swedish);
    ALTER TEXT SEARCH CONFIGURATION swedish_hunspell
      ALTER MAPPING FOR asciihword, asciiword, hword, hword_asciipart, hword_part, word
      WITH swedish_hunspell, swedish_stem;
    """)
  end

  def down do
    execute("""
    DROP TEXT SEARCH CONFIGURATION swedish_hunspell;
    DROP TEXT SEARCH DICTIONARY swedish_hunspell;
    """)
  end
end
